# Rebounding

ASide:
  - Room: "1a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
      LowBound: 7
      HighBound: 31
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    InternalEdges:
    - To: "cassette"
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "cassette"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
        
  - Room: "1a_cas"
    ReqEnd:
      Or:
      - Dashes: one
        Difficulty: hard
      - Dashes: two
        Difficulty: normal
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "cassette"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 160
        Y: 104
      
  - Room: "2a"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: in
      LowBound: 17
      HighBound: 22
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Left # secret exit blocked since end room
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "conditionBlock" # block off bubble to secret exit
      Update:
        Remove: true
    - Name: "torch"
      ID: 98
      Update:
        Remove: true
    - Name: "exitBlock"
      Update:
        Add: true
        X: 304
        Y: 464
        Width: 24
        Height: 64
        Values:
          tiletype: "1" # Dirt
      
  - Room: "Celeste_Comm"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Dashes: one
    Tweaks:
    - Name: "booster"
      Update:
        X: 296
      
      
BSide:
  - Room: "1b"
    Hub: true
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none # requires bubble
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: hard
    - To: "secret"
      ReqOut:
        Dashes: one
        Difficulty: hard
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "secret"
        ReqOut:
          Dashes: one
          Difficulty: normal
    - Room: "secret"
      Holes:
      - Side: Left
        Idx: 1
        Kind: out
      
  - Room: "2b"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      
      
CSide:
  - Room: "1c"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
      
  - Room: "ocmet"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none