# Calculated Maneuvers

ASide:
  - Room: "1a"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  # - Room: "1a_rando"
    # Hub: true
    # Holes:
    # - Side: Right
      # Idx: 0
      # Kind: inout
    # # blocked
    # - Side: Left
      # Idx: 0
      # Kind: none
    # - Side: Up
      # Idx: 0
      # Kind: none
    # - Side: Up
      # Idx: 1
      # Kind: none
    # - Side: Down
      # Idx: 2
      # Kind: none
    # InternalEdges:
    # - To: "exit"
      # ReqOut:
        # Dashes: two
        # Difficulty: perfect
    # Subrooms:
    # - Room: "exit"
      # Holes:
      # - Side: Left
        # Idx: 1
        # Kind: inout
      # - Side: Down
        # Idx: 0
        # Kind: unknown
      # - Side: Down
        # Idx: 1
        # Kind: inout
    # Tweaks:
    # - Name: "spawn"
      # X: 1000
      # Y: 96
      # Update:
        # Default: true
      
  - Room: "1a_cas"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Up
      Idx: 1
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "cassette"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 64
        Y: 64
      
  - Room: "2a"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
      
      
BSide:
  - Room: "1b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "2b"
    ReqEnd:
      Or:
      - Dashes: one
        Difficulty: hard
      - Dashes: two
        Difficulty: normal
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: unknown
    # blocked
    - Side: Up # secret removed
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    Tweaks:
    - Name: "dashBlock" # close off secret
      ID: 415
      Update:
        Values:
          canDash: false
      
      
CSide:
  - Room: "1c"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up # secret removed
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    Tweaks:
    - Name: "exitBlock" # block off secret
      Update:
        Add: true
        X: 1464
        Y: -8
        Width: 48
        Height: 16
        Values:
          tiletype: "6" # Stone