# Badeline's Castle

ASide:
  - Room: "0a"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: zero
        
  - Room: "1a"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: hard
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "1a_cas"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "cassette"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 216
        Y: 88
      
  - Room: "2a"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
      
      
BSide:
  - Room: "0a"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "heartGemDoor"
      Update:
        Remove: true
      
  - Room: "1b"
    Hub: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "secret"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
      InternalEdges:
      - To: "secret"
        ReqOut:
          Dashes: two
          Difficulty: normal
    - Room: "secret"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: one
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "2b"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
      
  - Room: "3b"
    ReqEnd:
      Or:
      - Dashes: one
        Difficulty: hard
      - Dashes: two
        Difficulty: normal
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
      

CSide:      
  - Room: "1c"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      New: true # dream block exit
      Kind: out
      LowBound: 393
      HighBound: 393
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
      
  - Room: "2c"
    ReqEnd:
      Dashes: one
      Difficulty: hard
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none